name: "SmallWindow21 Test Deploy"

on:
  push:
    #branches: [ ! main ]

jobs:
  tflint:
    name: "Run tflint on application"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform
    steps:
    - uses: actions/checkout@v2
      name: Checkout source code
    - uses: actions/cache@v2
      name: Cache plugin dir
      with:
        path: ~/.tflint.d/plugins
        key: ${{ matrix.os }}-tflint-${{ hashFiles('.tflint.hcl') }}
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Format
      id: fmt
      run: terraform fmt -recursive -check

    - name: Terraform Init
      id: init
      run: terraform init    
    - name: Setup TFLint
      uses: terraform-linters/setup-tflint@v1
      with:
        tflint_version: v0.29.0

    - name: Show version
      run: tflint --version

    - name: Init TFLint
      run: tflint --init

    - name: Run TFLint
      run: tflint --module -f compact |
           tflint --module security -f compact |
           tflint --module networking -f compact |
           tflint --module database -f compact | 
           tflint --module storage -f compact |
           tflint --module compute -f compact
           
  build-application:
    name: "Build Application"
    runs-on: ubuntu-latest
    needs: tflint
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: mvn -B clean install --file app/pom.xml
      - run: mkdir test && cp app/target/smallwindow-21-0.0.1-SNAPSHOT.jar test
      - uses: actions/upload-artifact@v2
        with:
          name: TestPackage
          path: test 